##
##                  DO NOT EDIT THIS FILE!!!
##
##        CHANGES WILL BE LOST ON YOUR NEXT UPGRADE.
##
##     EDIT XML::SAX::Machines::SiteConfig.pm INSTEAD!!!
##
##                         PLEASE.
##

##
## This file contains the "factory" settings for XML::SAX::Machines.
##
## Site specific settings should go in XML::SAX::Machines::SiteConfig

package XML::SAX::Machines::ConfigDefaults;

$LegalProcessorClassOptions = {
    ConstructWithHashedOptions =>
        q{Use Foo->new( { Handler => $h } ) instead of Foo->new( Handler => $h )},
},

$ProcessorClassOptions = {
    "XML::Filter::SAXT" => {
        ConstructWithHashedOptions => 1,
    },

    "XML::Filter::Distributor" => {
        ConstructWithHashedOptions => 1,
    },

    "XML::Filter::Tee" => {
        ConstructWithHashedOptions => 1,
    },

    "XML::SAX::Machine" => {
        ConstructWithHashedOptions => 1,
    },
}

##
##                  DO NOT EDIT THIS FILE!!!
##
##        CHANGES WILL BE LOST ON YOUR NEXT UPGRADE.
##
##     EDIT XML::SAX::Machines::SiteConfig.pm INSTEAD!!!
##
##                         PLEASE.
##
